import { visit } from "unist-util-visit";
import type { Plugin } from "unified";
import type { Root, Element } from "hast";

/**
 * Rehype plugin to clean up IDs generated by rehype-slug
 * Removes leading and trailing hyphens from id attributes
 */
export const rehypeCleanIds: Plugin<[], Root> = () => {
  return (tree) => {
    visit(tree, "element", (node: Element) => {
      if (node.properties && typeof node.properties.id === "string") {
        // Remove leading and trailing hyphens
        node.properties.id = node.properties.id.replace(/^-+|-+$/g, "");
      }
    });
  };
};
