// Auto-generated by generate-toc.ts - DO NOT EDIT MANUALLY
// Run: npm run generate-toc

export interface NavigationHeading {
  level: number
  text: string
  id: string
}

export interface NavigationDoc {
  title: string
  path: string
  headings: NavigationHeading[]
}

export const generatedNavigation: NavigationDoc[] = [
  {
    "title": "API Reference - Volcano SDK",
    "path": "/docs/api",
    "headings": [
      {
        "level": 1,
        "text": "API Reference",
        "id": "api-reference"
      },
      {
        "level": 2,
        "text": "agent(options?): AgentBuilder {#agent}",
        "id": "agentoptions-agentbuilder-{#agent}"
      },
      {
        "level": 3,
        "text": "Options",
        "id": "options"
      },
      {
        "level": 3,
        "text": "Methods",
        "id": "methods"
      },
      {
        "level": 4,
        "text": "Basic Methods",
        "id": "basic-methods"
      },
      {
        "level": 4,
        "text": "Advanced Pattern Methods",
        "id": "advanced-pattern-methods"
      },
      {
        "level": 2,
        "text": "Step Types {#step}",
        "id": "step-types-{#step}"
      },
      {
        "level": 3,
        "text": "LLM-Only Step",
        "id": "llm-only-step"
      },
      {
        "level": 3,
        "text": "Automatic MCP Tool Selection",
        "id": "automatic-mcp-tool-selection"
      },
      {
        "level": 3,
        "text": "Explicit MCP Tool Call",
        "id": "explicit-mcp-tool-call"
      },
      {
        "level": 3,
        "text": "Common Step Fields",
        "id": "common-step-fields"
      },
      {
        "level": 2,
        "text": "Step Results {#results}",
        "id": "step-results-{#results}"
      },
      {
        "level": 3,
        "text": "Example Usage",
        "id": "example-usage"
      },
      {
        "level": 2,
        "text": "RetryConfig {#retry-config}",
        "id": "retryconfig-{#retry-config}"
      },
      {
        "level": 3,
        "text": "Examples",
        "id": "examples"
      },
      {
        "level": 2,
        "text": "Utility Functions {#utilities}",
        "id": "utility-functions-{#utilities}"
      },
      {
        "level": 3,
        "text": "mcp(url, options?): MCPHandle",
        "id": "mcpurl,-options-mcphandle"
      },
      {
        "level": 3,
        "text": "discoverTools(handles): Promise<ToolDefinition[]>",
        "id": "discovertoolshandles-promise<tooldefinition[]>"
      },
      {
        "level": 2,
        "text": "Type Reference {#types}",
        "id": "type-reference-{#types}"
      },
      {
        "level": 3,
        "text": "LLMHandle",
        "id": "llmhandle"
      },
      {
        "level": 3,
        "text": "MCPHandle",
        "id": "mcphandle"
      },
      {
        "level": 3,
        "text": "ToolDefinition",
        "id": "tooldefinition"
      }
    ]
  },
  {
    "title": "Examples - Volcano SDK",
    "path": "/docs/examples",
    "headings": [
      {
        "level": 1,
        "text": "Examples",
        "id": "examples"
      },
      {
        "level": 2,
        "text": "Basic Examples {#basic}",
        "id": "basic-examples-{#basic}"
      },
      {
        "level": 3,
        "text": "basic.ts",
        "id": "basic.ts"
      },
      {
        "level": 3,
        "text": "automatic.ts",
        "id": "automatic.ts"
      },
      {
        "level": 3,
        "text": "providers.ts",
        "id": "providers.ts"
      },
      {
        "level": 2,
        "text": "Advanced Patterns {#patterns}",
        "id": "advanced-patterns-{#patterns}"
      },
      {
        "level": 3,
        "text": "parallel.ts",
        "id": "parallel.ts"
      },
      {
        "level": 3,
        "text": "branching.ts & branching-simple.ts",
        "id": "branching.ts-branching-simple.ts"
      },
      {
        "level": 3,
        "text": "loops.ts & loops-simple.ts",
        "id": "loops.ts-loops-simple.ts"
      },
      {
        "level": 3,
        "text": "sub-agents.ts & composition.ts",
        "id": "sub-agents.ts-composition.ts"
      },
      {
        "level": 3,
        "text": "advanced-patterns.ts",
        "id": "advanced-patterns.ts"
      },
      {
        "level": 2,
        "text": "Special Features {#features}",
        "id": "special-features-{#features}"
      },
      {
        "level": 3,
        "text": "streaming.ts",
        "id": "streaming.ts"
      },
      {
        "level": 2,
        "text": "Running Examples {#running}",
        "id": "running-examples-{#running}"
      },
      {
        "level": 3,
        "text": "Prerequisites",
        "id": "prerequisites"
      },
      {
        "level": 3,
        "text": "Set Environment Variables",
        "id": "set-environment-variables"
      },
      {
        "level": 3,
        "text": "Run an Example",
        "id": "run-an-example"
      },
      {
        "level": 2,
        "text": "More Examples {#more}",
        "id": "more-examples-{#more}"
      },
      {
        "level": 3,
        "text": "Contributing Examples",
        "id": "contributing-examples"
      }
    ]
  },
  {
    "title": "Features - Volcano SDK",
    "path": "/docs/features",
    "headings": [
      {
        "level": 1,
        "text": "Features",
        "id": "features"
      },
      {
        "level": 2,
        "text": "run() Method {#run}",
        "id": "run-method-{#run}"
      },
      {
        "level": 3,
        "text": "With Logging Callback",
        "id": "with-logging-callback"
      },
      {
        "level": 3,
        "text": "Return Value",
        "id": "return-value"
      },
      {
        "level": 3,
        "text": "Characteristics",
        "id": "characteristics"
      },
      {
        "level": 3,
        "text": "When to Use run()",
        "id": "when-to-use-run"
      },
      {
        "level": 2,
        "text": "stream() Method {#streaming}",
        "id": "stream-method-{#streaming}"
      },
      {
        "level": 3,
        "text": "Streaming with Progress Tracking",
        "id": "streaming-with-progress-tracking"
      },
      {
        "level": 3,
        "text": "When to Use Streaming",
        "id": "when-to-use-streaming"
      },
      {
        "level": 4,
        "text": "Use `stream()` for:",
        "id": "use-`stream`-for"
      },
      {
        "level": 4,
        "text": "Use `run()` for:",
        "id": "use-`run`-for"
      },
      {
        "level": 3,
        "text": "Characteristics",
        "id": "characteristics-1"
      },
      {
        "level": 2,
        "text": "Retries & Timeouts {#retries}",
        "id": "retries-timeouts-{#retries}"
      },
      {
        "level": 3,
        "text": "Timeouts",
        "id": "timeouts"
      },
      {
        "level": 3,
        "text": "Retry Strategies",
        "id": "retry-strategies"
      },
      {
        "level": 4,
        "text": "Immediate Retry (Default)",
        "id": "immediate-retry-default"
      },
      {
        "level": 4,
        "text": "Delayed Retry",
        "id": "delayed-retry"
      },
      {
        "level": 4,
        "text": "Exponential Backoff",
        "id": "exponential-backoff"
      },
      {
        "level": 3,
        "text": "Per-Step Override",
        "id": "per-step-override"
      },
      {
        "level": 3,
        "text": "Retry Semantics",
        "id": "retry-semantics"
      },
      {
        "level": 2,
        "text": "Step Hooks {#hooks}",
        "id": "step-hooks-{#hooks}"
      },
      {
        "level": 3,
        "text": "Hook Execution Order",
        "id": "hook-execution-order"
      },
      {
        "level": 3,
        "text": "Hook Characteristics",
        "id": "hook-characteristics"
      },
      {
        "level": 3,
        "text": "Use Cases",
        "id": "use-cases"
      },
      {
        "level": 2,
        "text": "Error Handling {#errors}",
        "id": "error-handling-{#errors}"
      },
      {
        "level": 3,
        "text": "Error Types",
        "id": "error-types"
      },
      {
        "level": 3,
        "text": "Error Metadata",
        "id": "error-metadata"
      },
      {
        "level": 3,
        "text": "Metadata Fields",
        "id": "metadata-fields"
      }
    ]
  },
  {
    "title": "Volcano SDK - Build MCP-powered AI Agents",
    "path": "/docs",
    "headings": [
      {
        "level": 1,
        "text": "Volcano SDK 🌋 {#introduction}",
        "id": "volcano-sdk-🌋-{#introduction}"
      },
      {
        "level": 3,
        "text": "Chainable API {#chainable-api}",
        "id": "chainable-api-{#chainable-api}"
      },
      {
        "level": 3,
        "text": "Automatic Tool Selection {#automatic-tool-selection}",
        "id": "automatic-tool-selection-{#automatic-tool-selection}"
      },
      {
        "level": 3,
        "text": "100s of Models {#100s-of-models}",
        "id": "100s-of-models-{#100s-of-models}"
      },
      {
        "level": 3,
        "text": "TypeScript-First {#typescript-first}",
        "id": "typescript-first-{#typescript-first}"
      },
      {
        "level": 3,
        "text": "Advanced Patterns {#advanced-patterns}",
        "id": "advanced-patterns-{#advanced-patterns}"
      },
      {
        "level": 3,
        "text": "Retries & Timeouts {#retries-timeouts}",
        "id": "retries-timeouts-{#retries-timeouts}"
      },
      {
        "level": 3,
        "text": "Streaming Workflows {#streaming-workflows}",
        "id": "streaming-workflows-{#streaming-workflows}"
      },
      {
        "level": 3,
        "text": "MCP Integration {#mcp-integration}",
        "id": "mcp-integration-{#mcp-integration}"
      },
      {
        "level": 3,
        "text": "Sub-Agent Composition {#sub-agent-composition}",
        "id": "sub-agent-composition-{#sub-agent-composition}"
      },
      {
        "level": 3,
        "text": "OpenTelemetry Observability {#opentelemetry-observability}",
        "id": "opentelemetry-observability-{#opentelemetry-observability}"
      },
      {
        "level": 3,
        "text": "MCP OAuth Authentication {#mcp-oauth-authentication}",
        "id": "mcp-oauth-authentication-{#mcp-oauth-authentication}"
      },
      {
        "level": 3,
        "text": "Performance Optimized {#performance-optimized}",
        "id": "performance-optimized-{#performance-optimized}"
      },
      {
        "level": 2,
        "text": "Installation {#installation}",
        "id": "installation-{#installation}"
      },
      {
        "level": 3,
        "text": "Optional Provider Dependencies {#optional-provider-dependencies}",
        "id": "optional-provider-dependencies-{#optional-provider-dependencies}"
      },
      {
        "level": 3,
        "text": "Optional Observability {#optional-observability}",
        "id": "optional-observability-{#optional-observability}"
      },
      {
        "level": 2,
        "text": "Quick Start {#quick-start}",
        "id": "quick-start-{#quick-start}"
      },
      {
        "level": 3,
        "text": "Hello World {#hello-world}",
        "id": "hello-world-{#hello-world}"
      },
      {
        "level": 3,
        "text": "Two-Step Agent with MCP Tools {#two-step-agent-with-mcp-tools}",
        "id": "two-step-agent-with-mcp-tools-{#two-step-agent-with-mcp-tools}"
      },
      {
        "level": 3,
        "text": "Multi-Provider Workflow {#multi-provider-workflow}",
        "id": "multi-provider-workflow-{#multi-provider-workflow}"
      },
      {
        "level": 3,
        "text": "Next Steps {#next-steps}",
        "id": "next-steps-{#next-steps}"
      },
      {
        "level": 2,
        "text": "Use Cases {#use-cases}",
        "id": "use-cases-{#use-cases}"
      },
      {
        "level": 3,
        "text": "Customer Support Automation {#customer-support-automation}",
        "id": "customer-support-automation-{#customer-support-automation}"
      },
      {
        "level": 3,
        "text": "Content Moderation Pipeline {#content-moderation-pipeline}",
        "id": "content-moderation-pipeline-{#content-moderation-pipeline}"
      },
      {
        "level": 3,
        "text": "Data Processing Workflows {#data-processing-workflows}",
        "id": "data-processing-workflows-{#data-processing-workflows}"
      },
      {
        "level": 3,
        "text": "Multi-Step Research Agent {#multi-step-research-agent}",
        "id": "multi-step-research-agent-{#multi-step-research-agent}"
      },
      {
        "level": 2,
        "text": "Volcano vs Others {#comparison}",
        "id": "volcano-vs-others-{#comparison}"
      },
      {
        "level": 3,
        "text": "When to Choose Volcano {#when-to-choose-volcano}",
        "id": "when-to-choose-volcano-{#when-to-choose-volcano}"
      },
      {
        "level": 2,
        "text": "Core Concepts {#core-concepts}",
        "id": "core-concepts-{#core-concepts}"
      },
      {
        "level": 3,
        "text": "Agents {#agents}",
        "id": "agents-{#agents}"
      },
      {
        "level": 3,
        "text": "Steps {#steps}",
        "id": "steps-{#steps}"
      },
      {
        "level": 3,
        "text": "Context & History {#context-history}",
        "id": "context-history-{#context-history}"
      },
      {
        "level": 3,
        "text": "Multi-Provider Workflows {#multi-provider-workflows}",
        "id": "multi-provider-workflows-{#multi-provider-workflows}"
      },
      {
        "level": 2,
        "text": "Questions or Feature Requests? {#questions}",
        "id": "questions-or-feature-requests-{#questions}"
      },
      {
        "level": 3,
        "text": "GitHub Repository {#github-repository}",
        "id": "github-repository-{#github-repository}"
      },
      {
        "level": 3,
        "text": "⭐ View on GitHub {#view-on-github}",
        "id": "⭐-view-on-github-{#view-on-github}"
      }
    ]
  },
  {
    "title": "MCP Tools - Volcano SDK",
    "path": "/docs/mcp-tools",
    "headings": [
      {
        "level": 1,
        "text": "MCP Tools",
        "id": "mcp-tools"
      },
      {
        "level": 2,
        "text": "Automatic Tool Selection {#automatic}",
        "id": "automatic-tool-selection-{#automatic}"
      },
      {
        "level": 3,
        "text": "How It Works",
        "id": "how-it-works"
      },
      {
        "level": 3,
        "text": "Controlling Tool Iterations",
        "id": "controlling-tool-iterations"
      },
      {
        "level": 3,
        "text": "Iteration Trade-offs",
        "id": "iteration-trade-offs"
      },
      {
        "level": 3,
        "text": "Multiple MCP Servers",
        "id": "multiple-mcp-servers"
      },
      {
        "level": 2,
        "text": "Explicit Tool Calling {#explicit}",
        "id": "explicit-tool-calling-{#explicit}"
      },
      {
        "level": 3,
        "text": "With LLM Step",
        "id": "with-llm-step"
      },
      {
        "level": 3,
        "text": "When to Use Explicit Calling",
        "id": "when-to-use-explicit-calling"
      },
      {
        "level": 2,
        "text": "MCP Authentication {#authentication}",
        "id": "mcp-authentication-{#authentication}"
      },
      {
        "level": 3,
        "text": "Handle-Level Authentication",
        "id": "handle-level-authentication"
      },
      {
        "level": 3,
        "text": "Agent-Level Authentication",
        "id": "agent-level-authentication"
      },
      {
        "level": 3,
        "text": "OAuth Authentication (Client Credentials)",
        "id": "oauth-authentication-client-credentials"
      },
      {
        "level": 3,
        "text": "Bearer Token Authentication",
        "id": "bearer-token-authentication"
      },
      {
        "level": 3,
        "text": "Mixed Authentication",
        "id": "mixed-authentication"
      },
      {
        "level": 3,
        "text": "Authentication Features",
        "id": "authentication-features"
      },
      {
        "level": 2,
        "text": "Connection Pooling & Performance {#connection-pooling}",
        "id": "connection-pooling-performance-{#connection-pooling}"
      },
      {
        "level": 3,
        "text": "Connection Pooling",
        "id": "connection-pooling"
      },
      {
        "level": 3,
        "text": "Tool Discovery Cache",
        "id": "tool-discovery-cache"
      },
      {
        "level": 3,
        "text": "Schema Validation",
        "id": "schema-validation"
      },
      {
        "level": 3,
        "text": "Configuration",
        "id": "configuration"
      }
    ]
  },
  {
    "title": "Observability - Volcano SDK",
    "path": "/docs/observability",
    "headings": [
      {
        "level": 1,
        "text": "Observability",
        "id": "observability"
      },
      {
        "level": 2,
        "text": "OpenTelemetry Integration {#opentelemetry}",
        "id": "opentelemetry-integration-{#opentelemetry}"
      },
      {
        "level": 3,
        "text": "Quick Start",
        "id": "quick-start"
      },
      {
        "level": 3,
        "text": "Installation",
        "id": "installation"
      },
      {
        "level": 2,
        "text": "Distributed Tracing {#traces}",
        "id": "distributed-tracing-{#traces}"
      },
      {
        "level": 3,
        "text": "Trace Hierarchy",
        "id": "trace-hierarchy"
      },
      {
        "level": 3,
        "text": "Span Attributes",
        "id": "span-attributes"
      },
      {
        "level": 3,
        "text": "Error Tracking",
        "id": "error-tracking"
      },
      {
        "level": 2,
        "text": "Metrics {#metrics}",
        "id": "metrics-{#metrics}"
      },
      {
        "level": 3,
        "text": "Available Metrics",
        "id": "available-metrics"
      },
      {
        "level": 3,
        "text": "Metric Labels",
        "id": "metric-labels"
      },
      {
        "level": 2,
        "text": "Observability Backends {#backends}",
        "id": "observability-backends-{#backends}"
      },
      {
        "level": 3,
        "text": "Jaeger (Distributed Tracing)",
        "id": "jaeger-distributed-tracing"
      },
      {
        "level": 3,
        "text": "Prometheus (Metrics)",
        "id": "prometheus-metrics"
      },
      {
        "level": 3,
        "text": "DataDog / NewRelic / Grafana Cloud",
        "id": "datadog-newrelic-grafana-cloud"
      },
      {
        "level": 3,
        "text": "Environment Variables",
        "id": "environment-variables"
      },
      {
        "level": 2,
        "text": "Advanced Configuration {#advanced}",
        "id": "advanced-configuration-{#advanced}"
      },
      {
        "level": 3,
        "text": "Custom Tracer and Meter",
        "id": "custom-tracer-and-meter"
      },
      {
        "level": 3,
        "text": "Disable Traces or Metrics",
        "id": "disable-traces-or-metrics"
      },
      {
        "level": 2,
        "text": "Best Practices {#best-practices}",
        "id": "best-practices-{#best-practices}"
      }
    ]
  },
  {
    "title": "Advanced Patterns - Volcano SDK",
    "path": "/docs/patterns",
    "headings": [
      {
        "level": 1,
        "text": "Advanced Patterns",
        "id": "advanced-patterns"
      },
      {
        "level": 2,
        "text": "Multi-LLM Workflows {#multi-llm}",
        "id": "multi-llm-workflows-{#multi-llm}"
      },
      {
        "level": 3,
        "text": "Basic Multi-Provider Workflow",
        "id": "basic-multi-provider-workflow"
      },
      {
        "level": 3,
        "text": "Cost-Optimized Pipeline",
        "id": "cost-optimized-pipeline"
      },
      {
        "level": 3,
        "text": "Multi-Provider with MCP Tools",
        "id": "multi-provider-with-mcp-tools"
      },
      {
        "level": 3,
        "text": "Conditional Provider Switching",
        "id": "conditional-provider-switching"
      },
      {
        "level": 3,
        "text": "Global Default with Per-Step Overrides",
        "id": "global-default-with-per-step-overrides"
      },
      {
        "level": 3,
        "text": "Benefits",
        "id": "benefits"
      },
      {
        "level": 2,
        "text": "Parallel Execution {#parallel}",
        "id": "parallel-execution-{#parallel}"
      },
      {
        "level": 3,
        "text": "Array Mode",
        "id": "array-mode"
      },
      {
        "level": 3,
        "text": "Named Dictionary Mode",
        "id": "named-dictionary-mode"
      },
      {
        "level": 3,
        "text": "Benefits",
        "id": "benefits-1"
      },
      {
        "level": 2,
        "text": "Conditional Branching {#branching}",
        "id": "conditional-branching-{#branching}"
      },
      {
        "level": 3,
        "text": "If/Else Branching",
        "id": "ifelse-branching"
      },
      {
        "level": 3,
        "text": "Switch/Case Branching",
        "id": "switchcase-branching"
      },
      {
        "level": 3,
        "text": "Use Cases",
        "id": "use-cases"
      },
      {
        "level": 2,
        "text": "Loops {#loops}",
        "id": "loops-{#loops}"
      },
      {
        "level": 3,
        "text": "While Loop",
        "id": "while-loop"
      },
      {
        "level": 3,
        "text": "For-Each Loop",
        "id": "for-each-loop"
      },
      {
        "level": 3,
        "text": "Retry Until Success",
        "id": "retry-until-success"
      },
      {
        "level": 3,
        "text": "Use Cases",
        "id": "use-cases-1"
      },
      {
        "level": 2,
        "text": "Sub-Agent Composition {#sub-agents}",
        "id": "sub-agent-composition-{#sub-agents}"
      },
      {
        "level": 3,
        "text": "Defining Reusable Sub-Agents",
        "id": "defining-reusable-sub-agents"
      },
      {
        "level": 3,
        "text": "Composing Sub-Agents",
        "id": "composing-sub-agents"
      },
      {
        "level": 3,
        "text": "Complex Composition",
        "id": "complex-composition"
      },
      {
        "level": 3,
        "text": "Benefits",
        "id": "benefits-2"
      },
      {
        "level": 2,
        "text": "Combined Patterns {#combined}",
        "id": "combined-patterns-{#combined}"
      }
    ]
  },
  {
    "title": "LLM Providers - Volcano SDK",
    "path": "/docs/providers",
    "headings": [
      {
        "level": 1,
        "text": "LLM Providers",
        "id": "llm-providers"
      },
      {
        "level": 3,
        "text": "Provider Support Matrix",
        "id": "provider-support-matrix"
      },
      {
        "level": 3,
        "text": "✅ OpenAI",
        "id": "✅-openai"
      },
      {
        "level": 3,
        "text": "✅ Anthropic",
        "id": "✅-anthropic"
      },
      {
        "level": 3,
        "text": "✅ Mistral",
        "id": "✅-mistral"
      },
      {
        "level": 3,
        "text": "✅ Llama",
        "id": "✅-llama"
      },
      {
        "level": 3,
        "text": "✅ AWS Bedrock",
        "id": "✅-aws-bedrock"
      },
      {
        "level": 3,
        "text": "✅ Google Vertex",
        "id": "✅-google-vertex"
      },
      {
        "level": 3,
        "text": "✅ Azure AI",
        "id": "✅-azure-ai"
      },
      {
        "level": 2,
        "text": "OpenAI Provider {#openai}",
        "id": "openai-provider-{#openai}"
      },
      {
        "level": 3,
        "text": "Authentication",
        "id": "authentication"
      },
      {
        "level": 3,
        "text": "Configuration",
        "id": "configuration"
      },
      {
        "level": 3,
        "text": "Options Parameters",
        "id": "options-parameters"
      },
      {
        "level": 3,
        "text": "Structured Outputs (JSON Schema Validation)",
        "id": "structured-outputs-json-schema-validation"
      },
      {
        "level": 4,
        "text": "Why Use Structured Outputs?",
        "id": "why-use-structured-outputs"
      },
      {
        "level": 4,
        "text": "Supported Models",
        "id": "supported-models"
      },
      {
        "level": 4,
        "text": "In Agent Workflows",
        "id": "in-agent-workflows"
      },
      {
        "level": 4,
        "text": "Structured Outputs vs Regular JSON Mode",
        "id": "structured-outputs-vs-regular-json-mode"
      },
      {
        "level": 2,
        "text": "Anthropic (Claude) Provider {#anthropic}",
        "id": "anthropic-claude-provider-{#anthropic}"
      },
      {
        "level": 3,
        "text": "Authentication",
        "id": "authentication-1"
      },
      {
        "level": 3,
        "text": "Configuration",
        "id": "configuration-1"
      },
      {
        "level": 3,
        "text": "Options Parameters",
        "id": "options-parameters-1"
      },
      {
        "level": 2,
        "text": "Mistral Provider {#mistral}",
        "id": "mistral-provider-{#mistral}"
      },
      {
        "level": 3,
        "text": "Authentication",
        "id": "authentication-2"
      },
      {
        "level": 3,
        "text": "Configuration",
        "id": "configuration-2"
      },
      {
        "level": 3,
        "text": "Options Parameters",
        "id": "options-parameters-2"
      },
      {
        "level": 2,
        "text": "Llama Provider {#llama}",
        "id": "llama-provider-{#llama}"
      },
      {
        "level": 3,
        "text": "Authentication",
        "id": "authentication-3"
      },
      {
        "level": 3,
        "text": "Configuration",
        "id": "configuration-3"
      },
      {
        "level": 3,
        "text": "Options Parameters",
        "id": "options-parameters-3"
      },
      {
        "level": 2,
        "text": "AWS Bedrock Provider {#bedrock}",
        "id": "aws-bedrock-provider-{#bedrock}"
      },
      {
        "level": 3,
        "text": "Authentication",
        "id": "authentication-4"
      },
      {
        "level": 3,
        "text": "Authentication Examples",
        "id": "authentication-examples"
      },
      {
        "level": 3,
        "text": "Configuration",
        "id": "configuration-4"
      },
      {
        "level": 3,
        "text": "Options Parameters",
        "id": "options-parameters-4"
      },
      {
        "level": 2,
        "text": "Google Vertex Studio Provider {#vertex}",
        "id": "google-vertex-studio-provider-{#vertex}"
      },
      {
        "level": 3,
        "text": "Authentication",
        "id": "authentication-5"
      },
      {
        "level": 3,
        "text": "Configuration",
        "id": "configuration-5"
      },
      {
        "level": 3,
        "text": "Options Parameters",
        "id": "options-parameters-5"
      },
      {
        "level": 2,
        "text": "Azure AI Provider {#azure}",
        "id": "azure-ai-provider-{#azure}"
      },
      {
        "level": 3,
        "text": "Authentication",
        "id": "authentication-6"
      },
      {
        "level": 3,
        "text": "Authentication Examples",
        "id": "authentication-examples-1"
      },
      {
        "level": 3,
        "text": "Configuration",
        "id": "configuration-6"
      },
      {
        "level": 3,
        "text": "Options Parameters",
        "id": "options-parameters-6"
      },
      {
        "level": 2,
        "text": "Creating a Custom Provider {#custom}",
        "id": "creating-a-custom-provider-{#custom}"
      },
      {
        "level": 3,
        "text": "LLMHandle Interface",
        "id": "llmhandle-interface"
      },
      {
        "level": 3,
        "text": "Example: Custom Provider",
        "id": "example-custom-provider"
      },
      {
        "level": 3,
        "text": "Using Your Custom Provider",
        "id": "using-your-custom-provider"
      },
      {
        "level": 3,
        "text": "Requirements",
        "id": "requirements"
      }
    ]
  }
]
